<Project>
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/bin/**;$(MSBuildProjectDirectory)/obj/**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'DVault.Tests.Shared' or '$(MSBuildProjectName)' == 'DVault.Tests.Unit' or '$(MSBuildProjectName)' == 'DVault.Tests.Integration'">
    <BaseOutputPath>$(MSBuildThisFileDirectory)bin/$(MSBuildProjectName)/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>